/*
	******************** IMPORTANTE ******************************
  SCRIPT DE CRIAÇÃO DO BANCO DE DADOS "spedia"
  ANTES DE APLICAR ESSE SCRIPT CONFERIR E, SE NECESSÁRIO, ALTERAR ENDEREÇOS E NOMES
*/

USE [master]
GO

CREATE DATABASE [spedia]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'spedia', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\spedia.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'spedia_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\spedia_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [spedia] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [spedia].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [spedia] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [spedia] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [spedia] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [spedia] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [spedia] SET ARITHABORT OFF 
GO

ALTER DATABASE [spedia] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [spedia] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [spedia] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [spedia] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [spedia] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [spedia] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [spedia] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [spedia] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [spedia] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [spedia] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [spedia] SET  DISABLE_BROKER 
GO

ALTER DATABASE [spedia] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [spedia] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [spedia] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [spedia] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [spedia] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [spedia] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [spedia] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [spedia] SET RECOVERY FULL 
GO

ALTER DATABASE [spedia] SET  MULTI_USER 
GO

ALTER DATABASE [spedia] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [spedia] SET DB_CHAINING OFF 
GO

ALTER DATABASE [spedia] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [spedia] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [spedia] SET  READ_WRITE 
GO

--CRIAÇÃO DO USUÁRIO QUE A APLICAÇÃO USA PARA ACESSO AO BANCO DE DADOS "spedia"

CREATE LOGIN [spediauser] WITH PASSWORD=N'7EkvN1N4Tr3qY967hSJ4jZBidri/KPPK9Fgqw5dge/o=', DEFAULT_DATABASE=[spedia], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

ALTER LOGIN [spediauser] DISABLE
GO